#!/bin/bash
#chmod +x calc_Rxy_outgroup.sh
#extract vcf that include outgroup
for i in all
do
        vcftools --vcf /path/all.snpeff.ann.vcf --keep ./$i --recode --recode-INFO-all --out $i
        vcftools --vcf ./$i.recode.vcf --recode --recode-INFO-all --max-missing 1.0 --out $i.nomissing
        cat $i.nomissing.recode.vcf | grep "#" >head
        cat $i.nomissing.recode.vcf | grep -v "#" >body.txt
        for j in {1..100}
        do
        shuf -n 1000000 body.txt > random.txt
        cat head random.txt >>new.vcf
        bcftools sort new.vcf -Oz -o new.sorted.vcf.gz
        tabix -p vcf new.sorted.vcf.gz
        bcftools norm -m -any new.sorted.vcf.gz -Oz -o xx.split.vcf.gz
bcftools view -m2 -M2 -v snps xx.split.vcf.gz -Oz -o xx.biallelic.snp.vcf.gz
bcftools index xx.biallelic.snp.vcf.gz

STRICT_DERIVED_ALT=1 ./calc_Rxy_outgroup.sh \
  xx.biallelic.snp.vcf.gz \
  Grey-tailed.txt \
  Common_Snipe.txt \
  outgroup.txt \
  result_XY.strict
#
cat result_XY.strict.Rxy.tsv >>result.csv
rm result_XY.strict.Rxy.*
rm xx.split.vcf.gz
rm xx.biallelic.snp.vcf.gz
rm xx.biallelic.snp.vcf.gz.csi
        rm new.vcf
rm random.txt
rm new.sorted.vcf.gz
rm new.sorted.vcf.gz.tbi
        done
rm ./$i.recode.vcf
rm $i.nomissing.recode.vcf
rm head
rm body.txt
done
